name: Documentation

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      # Additional steps to generate documentation in "docs" directory
      - name: Upload Documentation to Wiki
        uses: actions/kmcdon83/github-wiki-publish-action@1.0
        with:
          path: "docs"
        env:
          GH_PERSONAL_ACCESS_TOKEN: ${{ secrets.GH_REPO_TOKEN }}
